CREATE DATABASE IF NOT EXISTS chapati_sales_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE chapati_sales_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chapati_sales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sale_date DATE NOT NULL UNIQUE,
    quantity INT NULL,
    rate INT NOT NULL DEFAULT 12,
    total INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'No Order',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
